server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: mail-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:mail_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

aws:
  region: ${AWS_REGION:ap-southeast-1}
  ses:
    from-email: ${AWS_SES_FROM_EMAIL:no-reply@demo.com}
  sqs:
    mail-queue-url: ${AWS_SQS_MAIL_QUEUE_URL:http://localhost:4566/000000000000/mail-queue}

logging:
  level:
    root: INFO
    com.demo.mail: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: OFF
